export const ULKELER = [
  { tr: 'Avusturya', en: 'Austria', flag: '🇦🇹' },
  { tr: 'Belçika', en: 'Belgium', flag: '🇧🇪' },
  { tr: 'Danimarka', en: 'Denmark', flag: '🇩🇰' },
  { tr: 'Almanya', en: 'Germany', flag: '🇩🇪' },
  { tr: 'Fransa', en: 'France', flag: '🇫🇷' },
  { tr: 'İngiltere', en: 'United Kingdom', flag: '🇬🇧' },
  { tr: 'İtalya', en: 'Italy', flag: '🇮🇹' },
  { tr: 'Hollanda', en: 'Netherlands', flag: '🇳🇱' },
  { tr: 'Polonya', en: 'Poland', flag: '🇵🇱' },
  { tr: 'İspanya', en: 'Spain', flag: '🇪🇸' },
  { tr: 'İsveç', en: 'Sweden', flag: '🇸🇪' },
  { tr: 'İsviçre', en: 'Switzerland', flag: '🇨🇭' },
  { tr: 'ABD', en: 'United States', flag: '🇺🇸' },
  { tr: 'Avustralya', en: 'Australia', flag: '🇦🇺' },
  { tr: 'Kanada', en: 'Canada', flag: '🇨🇦' },
  { tr: 'S. Arabistan', en: 'Saudi Arabia', flag: '🇸🇦' },
  { tr: 'BAE', en: 'UAE', flag: '🇦🇪' },
  { tr: 'Japonya', en: 'Japan', flag: '🇯🇵' },
]
